-- Relational schema corresponding to the AI Control Center data model.
-- PostgreSQL is the runtime persistence layer. The control_center_state table stores the live application snapshot; the additional tables provide a relational extension/audit schema for future migrations.
create table if not exists users (id text primary key, username text not null, password_hash text not null, created_at timestamptz not null default now());
create table if not exists provider_accounts (id text primary key, provider text not null, account_name text not null, username text, account_id text, status text not null, permissions jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists provider_connections (id text primary key, provider_account_id text references provider_accounts(id) on delete cascade, label text, purpose text, description text, how_to_use text, last_checked_at timestamptz, last_used_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists provider_credentials (id text primary key, connection_id text not null references provider_connections(id) on delete cascade, encrypted_secret text not null, secret_fingerprint text not null, status text not null, permissions jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(connection_id));
create table if not exists projects (id text primary key, name text not null, description text, github_account_id text, repo_owner text, repo_name text, branch text not null default 'main', render_workspace_id text, render_service_id text, render_service_name text, domain text, build_command text, start_command text, archive_path text, upload_id text, env_var_names jsonb not null default '[]'::jsonb, last_deployment_at timestamptz, auto_fix boolean not null default false, status text not null);
create table if not exists gateway_keys (id text primary key, key_name text not null, key_prefix text not null, key_last4 text not null, key_hash text not null unique, description text, status text not null, rate_limit integer not null default 60, allowed_providers jsonb not null default '[]'::jsonb, allowed_accounts jsonb not null default '[]'::jsonb, allowed_browser_sessions jsonb not null default '[]'::jsonb, expires_at timestamptz, permission_version integer not null default 1, capabilities jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), last_used_at timestamptz);
create table if not exists browser_sessions (id text primary key, session_name text not null, provider_account_id text, profile_name text not null, status text not null, current_url text, current_title text, active_tab text, last_activity_at timestamptz, waiting_human boolean not null default false, handoff_reason text, created_at timestamptz not null default now());
create table if not exists tasks (id text primary key, agent text not null, request text not null, plan jsonb not null default '[]'::jsonb, status text not null, current_step integer not null default 0, total_steps integer not null default 0, result jsonb, error text, gateway_key_id text references gateway_keys(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists task_steps (id text primary key, task_id text not null references tasks(id) on delete cascade, title text not null, status text not null, timestamp timestamptz not null default now(), details text);
create table if not exists deployments (id text primary key, project_id text, project_name text not null, provider text not null, account_id text, service_id text, deployment_id text not null, commit_hash text, commit_message text, status text not null, build_logs jsonb not null default '[]'::jsonb, duration_ms bigint, url text, error_diagnosis jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists activity_logs (id text primary key, timestamp timestamptz not null default now(), request_id text not null, actor text not null, agent_id text, gateway_key_id text, provider text, account text, operation text not null, target text, capability text, status text not null, duration_ms bigint not null default 0, error_category text, safe_error_message text, human_approval boolean, browser_session_id text, deployment_id text);
create table if not exists security_events (id text primary key, timestamp timestamptz not null default now(), event_type text not null, actor text not null, severity text not null, details text not null, resolved boolean not null default false);
create table if not exists token_requests (id text primary key, name text not null, provider text not null, account text not null, requested_by text not null, description text not null, how_to_use text not null, requested_permissions jsonb not null default '[]'::jsonb, encrypted_token text not null, token_fingerprint text not null, token_last4 text, status text not null, created_at timestamptz not null default now());
create table if not exists resource_links (id text primary key, source_id text not null, target_id text not null, relation text not null, created_at timestamptz not null default now());
create table if not exists domains (id text primary key, domain_name text not null, provider text not null, zone_id text, status text not null, ssl_status text, records jsonb not null default '[]'::jsonb, checked_at timestamptz not null default now());
create table if not exists dns_resources (id text primary key, domain_id text references domains(id) on delete cascade, record_type text not null, name text not null, content text not null, ttl integer, proxied boolean);
create table if not exists notifications (id text primary key, type text not null, title text not null, message text not null, read boolean not null default false, created_at timestamptz not null default now());
create table if not exists service_connectors (id text primary key, provider text not null, status text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists webhook_events (id text primary key, provider text not null, event_type text not null, signature_valid boolean not null, payload jsonb, created_at timestamptz not null default now());
create table if not exists provider_health (id text primary key, connection_id text references provider_connections(id) on delete cascade, healthy boolean not null, latency_ms integer, message text, checked_at timestamptz not null default now());
create table if not exists cost_checks (id text primary key, provider text not null, operation text not null, policy text not null, allowed boolean not null, reason text, checked_at timestamptz not null default now());
create table if not exists free_option_checks (id text primary key, provider text not null, service_name text not null, is_free boolean not null, source_url text, notes text not null, checked_at timestamptz not null default now());
create index if not exists activity_logs_gateway_idx on activity_logs(gateway_key_id, timestamp desc);
create index if not exists activity_logs_task_idx on activity_logs(request_id);
create index if not exists deployments_project_idx on deployments(project_id, created_at desc);
create index if not exists provider_connections_provider_idx on provider_connections(provider_account_id);

create table if not exists control_center_state (id integer primary key check (id = 1), version integer not null default 1, state jsonb not null, updated_at timestamptz not null default now());
