export interface CapabilityDefinition {
  id: string;
  group: 'github' | 'render' | 'cloudflare' | 'vercel' | 'netlify' | 'supabase' | 'digitalocean' | 'browser' | 'system';
  name: string;
  description: string;
  riskLevel: 'low' | 'medium' | 'high';
  dangerous: boolean;
  defaultGranted: boolean;
}

export const SYSTEM_CAPABILITIES: CapabilityDefinition[] = [
  // GitHub
  {
    id: 'github.read',
    group: 'github',
    name: 'GitHub Read Access',
    description: 'General read-only access to GitHub accounts and repositories',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.account.read',
    group: 'github',
    name: 'Inspect Accounts',
    description: 'Inspect connected GitHub account profiles and identities',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.repository.list',
    group: 'github',
    name: 'List Repositories',
    description: 'List and search repositories across connected accounts',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.repository.create',
    group: 'github',
    name: 'Create Repository',
    description: 'Create new public or private repositories under authorized accounts',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.repository.read',
    group: 'github',
    name: 'Read Repository Content',
    description: 'Inspect repository metadata, commits, branches, and files',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.repository.write',
    group: 'github',
    name: 'Write to Repository',
    description: 'Push commits, create branches, and update file contents',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'github.repository.delete',
    group: 'github',
    name: 'Delete Repository',
    description: 'Permanently delete repositories (requires explicit human confirmation)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'github.branch.read',
    group: 'github',
    name: 'Read Branches',
    description: 'List branches and inspect branch pointers',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.branch.write',
    group: 'github',
    name: 'Create / Modify Branches',
    description: 'Create new branches and update refs',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'github.commit.read',
    group: 'github',
    name: 'Read Commits',
    description: 'Inspect commit logs, diffs, and authorship',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.commit.write',
    group: 'github',
    name: 'Create Commits',
    description: 'Author commits and push revisions',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'github.file.read',
    group: 'github',
    name: 'Read Files',
    description: 'Retrieve raw file contents from repositories',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'github.file.write',
    group: 'github',
    name: 'Write Files',
    description: 'Create or edit individual repository files',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },

  // Render
  {
    id: 'render.account.read',
    group: 'render',
    name: 'Render Account Inspection',
    description: 'Read Render workspace and user identity metadata',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'render.workspace.read',
    group: 'render',
    name: 'Render Workspace Read',
    description: 'List workspaces and owners configured in Render',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'render.service.list',
    group: 'render',
    name: 'List Services',
    description: 'List web services, static sites, background workers, and databases',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'render.service.read',
    group: 'render',
    name: 'Read Service Details',
    description: 'Inspect service configuration, environment variables names, and metrics',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'render.service.create',
    group: 'render',
    name: 'Create Service',
    description: 'Create new web services or static sites in selected workspace',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'render.service.configure',
    group: 'render',
    name: 'Configure Service',
    description: 'Update build command, start command, and environment configuration',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'render.deploy',
    group: 'render',
    name: 'Trigger Deploy',
    description: 'Trigger deployment runs and redeploy existing services',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'render.logs',
    group: 'render',
    name: 'Inspect Logs',
    description: 'Retrieve build and deployment runtime execution logs',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'render.restart',
    group: 'render',
    name: 'Restart Service',
    description: 'Restart running web service instances',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'render.domain.read',
    group: 'render',
    name: 'Read Domains',
    description: 'Inspect custom domains attached to Render services',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'render.domain.write',
    group: 'render',
    name: 'Attach Custom Domain',
    description: 'Add or verify custom domains on Render services',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'render.rollback',
    group: 'render',
    name: 'Rollback Deployment',
    description: 'Deploy a previously known Render deployment revision after explicit confirmation',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'render.service.delete',
    group: 'render',
    name: 'Delete Service',
    description: 'Permanently remove Render web service or worker (requires confirmation)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },

  // Browser Automation
  {
    id: 'browser.navigate',
    group: 'browser',
    name: 'Browser Navigation',
    description: 'Open web pages, refresh, back, forward',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.click',
    group: 'browser',
    name: 'Browser Click / Tap',
    description: 'Click buttons, links, and interactive elements',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.type',
    group: 'browser',
    name: 'Browser Text Input',
    description: 'Type into search inputs and regular forms',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.copy',
    group: 'browser',
    name: 'Browser Copy',
    description: 'Copy text from web pages',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.paste',
    group: 'browser',
    name: 'Browser Paste',
    description: 'Paste text into target inputs',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.scroll',
    group: 'browser',
    name: 'Browser Scroll',
    description: 'Scroll viewport to reveal content',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.tabs',
    group: 'browser',
    name: 'Browser Tab Management',
    description: 'Open, switch, and close browser tabs',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.screenshot',
    group: 'browser',
    name: 'Browser Screenshot',
    description: 'Capture screenshot of current tab for inspection',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.read_page',
    group: 'browser',
    name: 'Browser Content Inspection',
    description: 'Read visible text and structured element tree',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'browser.human_handoff',
    group: 'browser',
    name: 'Human Handoff Request',
    description: 'Pause automation for CAPTCHA, 2FA, or verification',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },

  // SENSITIVE BROWSER CAPABILITIES - BLOCKED BY DEFAULT
  {
    id: 'browser.download',
    group: 'browser',
    name: 'Browser File Download',
    description: 'Allow file downloads from web sessions (BLOCKED by default)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.upload',
    group: 'browser',
    name: 'Browser File Upload',
    description: 'Allow file uploads to web sessions (BLOCKED by default)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.cookie.read',
    group: 'browser',
    name: 'Read Cookies',
    description: 'Read session cookies (BLOCKED by default for security)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.cookie.write',
    group: 'browser',
    name: 'Write Cookies',
    description: 'Inject cookies (BLOCKED by default)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.cookie.delete',
    group: 'browser',
    name: 'Delete Cookies',
    description: 'Purge cookies (BLOCKED by default)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.storage.read',
    group: 'browser',
    name: 'Read Local Storage',
    description: 'Extract raw localStorage/sessionStorage (BLOCKED)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.storage.write',
    group: 'browser',
    name: 'Write Local Storage',
    description: 'Mutate browser storage (BLOCKED)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.password.read',
    group: 'browser',
    name: 'Extract Passwords',
    description: 'Read browser saved passwords (STRICTLY BLOCKED)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
  {
    id: 'browser.permission.grant',
    group: 'browser',
    name: 'Grant Device Permissions',
    description: 'Auto-grant camera, mic, or geolocation permissions (BLOCKED)',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },


  {
    id: 'project.read',
    group: 'system',
    name: 'Project Metadata Read',
    description: 'Read project metadata required for authorized Gateway task execution',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'system.audit',
    group: 'system',
    name: 'System Audit',
    description: 'Run workspace diagnostic audits without exposing provider secrets',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },

  // Gateway / system discovery
  {
    id: 'gateway.file.download',
    group: 'system',
    name: 'API File Download',
    description: 'Allow an external AI to stream an explicitly authorized API resource to itself without storing it in the workspace',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'gateway.connections.read',
    group: 'system',
    name: 'Read Authorized Connections',
    description: 'Discover the provider connection metadata explicitly allowed to this Gateway key',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: false,
  },
  {
    id: 'gateway.activity.read',
    group: 'system',
    name: 'Read Own Gateway Activity',
    description: 'Read activity generated by this Gateway key',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'gateway.task.create',
    group: 'system',
    name: 'Create Gateway Tasks',
    description: 'Create asynchronous tasks through the Gateway',
    riskLevel: 'medium',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'gateway.task.read',
    group: 'system',
    name: 'Read Gateway Tasks',
    description: 'Read tasks created by this Gateway key',
    riskLevel: 'low',
    dangerous: false,
    defaultGranted: true,
  },
  {
    id: 'gateway.token.request',
    group: 'system',
    name: 'Request API Token Import',
    description: 'Submit a newly discovered API credential to the workspace for owner approval and encrypted storage',
    riskLevel: 'high',
    dangerous: true,
    defaultGranted: false,
  },
];
